### ISSUE TITLE
Models collector does not work with October (Laravel 5.5 only)

### ISSUE THREAD

**Issue by bennothommo** [scottbedard/oc-debugbar-plugin#33]
The models collector for `barryvdh/laravel-debugbar` does not seem to work with October.

```
[Wed May  6 12:59:41 2020] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Barryvdh\Debugbar\DataCollector\ModelsCollector::Barryvdh\Debugbar\DataCollector\{closure}(), 1 passed and exactly 2 expected in /home/ben/Projects/Personal/october/vendor/barryvdh/laravel-debugbar/src/DataCollector/ModelsCollector.php:23
```

It seems to stem from an incompatibility with how our wildcard events are passed to listeners. Release 3.3.2 of `barryvdh/laravel-debugbar` made the models collector enabled by default (don't worry @LukeTowers, it wasn't your PR :P).

You can replicate this by changing `collectors.models` to `true` in `plugins/rainlab/debugbar/config/config.php`.

**Comment by LukeTowers** [comment]
This is because the fix to the core required to make this work is in the Laravel 6 branch as it's technically a bit of a breaking change. Just leave it as disabled in the default config until the L6 upgrade is finished.

**Comment by bennothommo** [comment]
@LukeTowers should we hard-code it to "false" on a build that doesn't have L6, just to stave off any future bug reports? I suppose it's probably not critical given we'd be encouraging people to move to L6 when it's out.

**Comment by LukeTowers** [comment]
Nah, it's already set to false in the config, once we fix the package registration that should be enough.
